openapi: 3.0.1
info:
  title: PrimeT-demo-mi-soap-api
  description: API Definition of PrimeT-demo-mi-soap-api
  version: 1.0.0
servers:
- url: http://localhost:8290/demo
paths:
  /countries/{country}:
    get:
      parameters:
      - name: country
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response